title: WOW@USC
description: This site contains helpful documentation for members of our research lab
theme: just-the-docs

url: https://wow-at-usc.github.io/docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
